### ISSUE TITLE
[Bug]: No forwarding of Sass variables to vue sfc compiler

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [storybookjs/addon-styling#79] opened 2023-08-03 13:54 UTC
Not quite sure where the bug actually belongs. I guess the sass preprocessor is already done before the vue sfc processor reports that it also has some sass to preprocess.

https://github.com/storybookjs/storybook/issues/23705

**Comment by Integrayshaun** [comment] 2023-08-03 13:56
Hi @sschneider-ihre-pvs 👋 
Are you using `@storybook/addon-styling` to configure sass in your storybook project?

Can I see your `main.(js|ts)` file, please?

**Comment by sschneider-ihre-pvs** [comment] 2023-08-04 08:42
<details>
<summary>envinfo storybook packages</summary>

```
    @storybook/addon-actions: 7.0.23 => 7.0.23
    @storybook/addon-backgrounds: 7.0.23 => 7.0.23
    @storybook/addon-controls: 7.0.23 => 7.0.23
    @storybook/addon-docs: 7.0.23 => 7.0.23
    @storybook/addon-essentials: 7.0.22 => 7.0.22
    @storybook/addon-interactions: 7.0.22 => 7.0.22
    @storybook/addon-links: 7.0.22 => 7.0.22
    @storybook/addon-measure: 7.0.23 => 7.0.23
    @storybook/addon-outline: 7.0.23 => 7.0.23
    @storybook/addon-storysource: 7.0.23 => 7.0.23
    @storybook/addon-styling: 1.3.0 => 1.3.0
    @storybook/addon-toolbars: 7.0.23 => 7.0.23
    @storybook/addon-viewport: 7.0.23 => 7.0.23
    @storybook/blocks: 7.0.23 => 7.0.23
    @storybook/core-server: 7.0.22 => 7.0.22
    @storybook/jest: ^0.1.0 => 0.1.0
    @storybook/testing-library: 0.0.14-next.2 => 0.0.14-next.2
    @storybook/vue3: 7.0.22 => 7.0.22
    @storybook/vue3-webpack5: 7.0.22 => 7.0.22
    storybook-addon-apollo-client: 5.0.0 => 5.0.0
    storybook-addon-module-mock: 1.0.13 => 1.0.13
    storybook-vue3-router: 4.0.0 => 4.0.0
```

</details>

**Comment by Integrayshaun** [comment] 2023-08-04 13:10
Sweet! Okay 😁 

1. Remove addon-styling from your addon array in `main.js`
2. Run `yarn add -D @storybook/addon-styling@2.0.2-next.3 style-loader css-loader sass-loader resolve-url-loader`
3. Run `yarn addon-styling-setup`
4. Check the additions to `main.js` with addon-styling's new API
5. Add your `indentedSyntax` setting into `sass-options`
6. Run storybook

**Comment by sschneider-ihre-pvs** [comment] 2023-08-07 08:11
What new api?

**Comment by sschneider-ihre-pvs** [comment] 2023-08-07 08:15
Oh the one the wizard is inserting I got it.

**Comment by sschneider-ihre-pvs** [comment] 2023-08-07 08:19
same error

**Comment by Integrayshaun** [comment] 2023-08-08 13:19
It looks like you need a different loader to inject your sass variables into SFC files. Try replacing `style-loader` with `vue-style-loader` at the top of your `use` array.

```js
{
  name: "@storybook/addon-styling",
  options: {
    rules: [
       // Other rules ommitted
      {
        test: /\.s[ac]ss$/,
        sideEffects: true,
        use: [
          // Use vue-style-loader instead of style-loader
          require.resolve("vue-style-loader"), {
          loader: require.resolve("css-loader"),
          options: {
            importLoaders: 2
          }
        }, require.resolve("resolve-url-loader"), {
          loader: require.resolve("sass-loader"),
          options: {
            implementation: require.resolve("sass"),
            sourceMap: true,
            sassOptions: {},
          }
        }]
      }]
  }
}
```

Then follow this [section](https://vue-loader.vuejs.org/guide/pre-processors.html#sharing-global-variables) of the docs to look at prepending your sass variables

**Comment by sschneider-ihre-pvs** [comment] 2023-08-09 08:13
additionalData does not seem to work as expected. sass-loader complaints about `@use` before `@forward` and such, because it may be conflicting with already available files that have `@use` or `@forward` in them.

**Comment by sschneider-ihre-pvs** [comment] 2023-08-09 08:14
And also is unable to find relative imports.

**Comment by Integrayshaun** [comment] 2023-08-11 15:20
Can you share a reproduction of this issue? I'd like to have a deeper look

**Comment by sschneider-ihre-pvs** [comment] 2023-08-29 12:42
I guess I cannot since it is an internal project.

**Comment by Integrayshaun** [comment] 2023-08-29 12:55
@sschneider-ihre-pvs It doesn't need to be your internal project. If you run `npx storybook@latest sandbox` you can set up a bare bones example app to reproduce the error

**Comment by sschneider-ihre-pvs** [comment] 2023-08-30 13:21
I worked around the issue now with going back and use `@import` instead of `@use` seems to be the only way.

**Comment by Integrayshaun** [comment] 2023-08-30 13:53
Okay, I'm glad to hear that you were able to find a workaround.

Without a reproduction I'm going to close this for now but happy to reopen the issue if someone can provide a repro

**Closed by Integrayshaun** 2023-08-30 13:53 UTC
Labels: bug
