### ISSUE TITLE
[Bug] Addon was loaded twice

### ISSUE THREAD

**Issue by markokos01** [storybookjs/addon-styling#80] opened 2023-08-07 09:09 UTC
### Describe the bug

After I installed addon and listed it in main.ts, I got an error:

`@storybook/addon-styling was loaded twice, this could have bad side-effects`

### Steps to reproduce the behavior

1. Install addon
2. Add addon to main.ts
3. Run storybook
4. See console

### Expected behavior

I do not exect any error in the console.

### Environment

 - OS: macOS Ventura 13.4.1
 - Node.js version: v16.17.0
 - NPM version: 6.14.16
 - Browser (if applicable): Chrome
 - Browser version (if applicable): 115.0.5790.170

**Comment by dkario** [comment] 2023-08-07 23:20
might be duplicate of #67

**Comment by sookmax** [comment] 2023-08-15 17:01
@Integrayshaun hey this issue seems to be caused by the export `managerEntries` from `src/preset.ts`. In particular, It seems `addon-styling` is registered twice because of having both `src/manager.ts` and `managerEntries` in `src/preset.ts` at the same time.

## Screen captures

<img width="2032" alt="Screenshot 2023-08-16 at 1 48 41 AM" src="https://github.com/storybookjs/addon-styling/assets/71210554/22cb45ed-e273-4cc3-9cba-d30e0f570ce0">

---

<img width="1470" alt="Screenshot 2023-08-16 at 1 51 40 AM" src="https://github.com/storybookjs/addon-styling/assets/71210554/ddd2392f-b8c4-4afd-aefd-272c14d644da">

---

<img width="2032" alt="Screenshot 2023-08-16 at 1 54 01 AM" src="https://github.com/storybookjs/addon-styling/assets/71210554/b7056839-7cf6-4afe-8149-7d259481970e">

**Comment by Integrayshaun** [comment] 2023-08-15 17:36
Hey @sookmax that's a great catch!!! I'll get a patch out for this today

**Comment by Integrayshaun** [comment] 2023-08-24 14:12
Hey folks! I have a canary build that i'm testing for this right now. Can anyone try out `1.3.7--canary.88.040cffe.0`?

**Comment by sookmax** [comment] 2023-08-25 09:19
@Integrayshaun Hey Shaun nice job! looks like the warnings gone with the canary version 👍

**Closed** 2023-08-25 12:10 UTC
Labels: bug
